[tool.poetry]
name = "csv-converter"
version = "0.1.0"
description = ""
authors = ["PabloZalem <zalem.pablo@yahoo.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
